// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLyBNpO4cURWi1D_j7tfIMTi9cf2Toes',
    appId: '1:90519708206:web:b3400e45b0ca258121f5bf',
    messagingSenderId: '90519708206',
    projectId: 'flutterfirebase-f2375',
    authDomain: 'flutterfirebase-f2375.firebaseapp.com',
    storageBucket: 'flutterfirebase-f2375.appspot.com',
    measurementId: 'G-8SBC1P5GYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCszZFf6xZOkkr2aAUU3k9yUJl4fWs8lY',
    appId: '1:90519708206:android:21eef73a019aa6dc21f5bf',
    messagingSenderId: '90519708206',
    projectId: 'flutterfirebase-f2375',
    storageBucket: 'flutterfirebase-f2375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx5STSS-rk2iqzNWerDPXdk8dWthgse1I',
    appId: '1:90519708206:ios:b95a83872263f5b521f5bf',
    messagingSenderId: '90519708206',
    projectId: 'flutterfirebase-f2375',
    storageBucket: 'flutterfirebase-f2375.appspot.com',
    iosClientId: '90519708206-uqjm1m2rt8ebttnmod54rd4370qmi9u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myflutterapp',
  );
}
